---
es_namespace: elasticsearch
es_version: "9.4.1"
es_image: "docker.elastic.co/elasticsearch/elasticsearch"
kibana_version: "9.4.1"
kibana_image: "docker.elastic.co/kibana/kibana"
es_cluster_name: "platform-es"
es_license_type: "basic"

es_master_replicas: "{{ 3 if tier in ['medium', 'production'] else 1 }}"
es_data_replicas: "{{ 2 if tier == 'production' else 1 }}"

es_master_memory_req: "{{ '2Gi' if tier in ['medium', 'production'] else '1Gi' }}"
es_master_memory_lim: "{{ '3Gi' if tier in ['medium', 'production'] else '1536Mi' }}"
es_master_cpu_req: "{{ '500m' if tier in ['medium', 'production'] else '100m' }}"
es_master_cpu_lim: "{{ '1000m' if tier in ['medium', 'production'] else '500m' }}"
es_master_heap: "{{ '1g' if tier in ['medium', 'production'] else '512m' }}"
es_master_storage: "{{ '30Gi' if tier == 'production' else '20Gi' }}"

es_data_memory_req: "{{ '4Gi' if tier == 'production' else '2Gi' if tier == 'medium' else '1536Mi' }}"
es_data_memory_lim: "{{ '4Gi' if tier == 'production' else '2Gi' }}"
es_data_cpu_req: "{{ '1000m' if tier == 'production' else '750m' if tier == 'medium' else '250m' }}"
es_data_cpu_lim: "{{ '2000m' if tier == 'production' else '1000m' }}"
es_data_heap: "{{ '2g' if tier == 'production' else '1g' }}"
es_data_storage: "{{ '150Gi' if tier == 'production' else '100Gi' if tier == 'medium' else '20Gi' }}"

kibana_replicas: 1
kibana_memory_req: "{{ '768Mi' if tier in ['medium', 'production'] else '384Mi' }}"
kibana_memory_lim: "{{ '1536Mi' if tier in ['medium', 'production'] else '768Mi' }}"
kibana_cpu_req: "{{ '500m' if tier in ['medium', 'production'] else '100m' }}"
kibana_cpu_lim: "{{ '500m' if tier in ['medium', 'production'] else '250m' }}"

es_kibana_domain: "kibana.{{ domain }}"
