extends: default
rules:
  line-length: disable
  truthy: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-after: 1
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  indentation:
    indent-sequences: whatever
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
ignore: |
  .git/
  .venv/
  node_modules/
  __pycache__/
  .pre-commit-config.yaml
  roles/k8s-cluster-management/
  roles/k8s-gitops/
  roles/k8s-observability/
  roles/generate-secrets/
  roles/network-security/
  roles/object-storage/
  roles/k8s-autoscaling/
  roles/apm-server/
  templates/
  inventory.example
