---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: storage
spec:
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
    - port: http
      path: /v1/sys/metrics
      params:
        format: [prometheus]
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  namespace: postgres
spec:
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/role: exporter
  endpoints:
    - port: exporter
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  endpoints:
    - port: https
      path: /_prometheus/metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal
  namespace: temporal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
  endpoints:
    - port: metrics
      interval: 30s
