{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "opwerf.name" . }}-dashboard
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.ingress.gatewayName }}
      namespace: {{ .Values.ingress.gatewayNamespace }}
  hostnames:
    - {{ .Values.ingress.dashboardHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opwerf.name" . }}-dashboard
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "opwerf.name" . }}-api
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.ingress.gatewayName }}
      namespace: {{ .Values.ingress.gatewayNamespace }}
  hostnames:
    - {{ .Values.ingress.apiHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opwerf.name" . }}-api
          port: 8080
{{- end }}
