---
apm_namespace: elasticsearch
apm_version: "9.4.3"
apm_image: "docker.elastic.co/apm/apm-server"
apm_replicas: "{{ apm.replicas | default(2 if resource_tier in ['medium', 'production'] else 1) }}"

apm_memory_req: "{{ apm.memory_request | default('768Mi' if resource_tier in ['medium', 'production'] else '384Mi') }}"
apm_memory_lim: "{{ apm.memory_limit | default('1536Mi' if resource_tier in ['medium', 'production'] else '768Mi') }}"
apm_cpu_req: "{{ apm.cpu_request | default('500m' if resource_tier in ['medium', 'production'] else '100m') }}"
apm_cpu_lim: "{{ apm.cpu_limit | default('1500m' if resource_tier in ['medium', 'production'] else '750m') }}"

apm_es_host: "elasticsearch.elasticsearch.svc.cluster.local"
apm_es_port: 9200
apm_es_scheme: "https"
apm_es_user: "elastic"

# ILM retention (auto-delete old traces)
apm_ilm_hot_max_size: "{{ apm.ilm_hot_max_size | default('30gb') }}"
apm_ilm_hot_max_age: "{{ apm.ilm_hot_max_age | default('7d') }}"
apm_ilm_delete_after: "{{ apm.ilm_delete_after | default('14d') }}"

apm_otlp_grpc_port: 8200
apm_otlp_http_port: 8200
