---
# E2B handlers

- name: Restart e2b orchestrator
  ansible.builtin.systemd:
    name: e2b-orchestrator
    state: restarted
  listen: restart e2b orchestrator

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
